PREFIX := "/usr/local"

[doc('Generate the manual page for tempo(1). Requires scdoc.')]
build:
	scdoc < tempo.1.scd > tempo.1

[doc('Copy the manual page to $PREFIX.')]
install: build
	mkdir -p "{{PREFIX}}/share/man/man1"
	install -m644 tempo.1 "{{PREFIX}}/share/man/man1/tempo.1"

[doc('Remove the manual page from $PREFIX.')]
uninstall:
	rm -f "{{PREFIX}}/share/man/man1/tempo.1"

[doc('Remove local build artifacts.')]
clean:
	rm -vf tempo.1
